name    'theforeman-git'
version '1.2.0-rc2'
source 'git://github.com/theforeman/puppet-git'
author 'theforeman'
license 'GPLv3+'
summary 'git installation and configuration'
description 'Module for configuring git'
project_page 'http://github.com/theforeman/foreman-installer'
